Hospital Bed Expansion
CiscoDevNet/webex-contact-center-widget-starter pull request #26
Opened 2021-01-29 20:04 UTC by elenagiere

Hospital bed Expansion
<img width="975" alt="Screen Shot 2021-01-29 at 11 14 46 AM" src="https://user-images.githubusercontent.com/15151981/106321967-f8115a00-6229-11eb-9428-2fde4c091a95.png">

I still have a few styling tweaks to make as well has handle more loading and error handling cases.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Please check if the PR fulfills these requirements
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## What kind of change does this PR introduce?
#### (Bug fix, feature, docs update, ...)

`[Type here]`

## What is the current behavior?
#### (You can link to an open issue)

`[Type here]`

## What is the new behavior
#### (if this is a feature change)?

`[Type here]`

## Does this PR introduce a breaking change?
#### (What changes might users need to make in their application due to this PR?)

`[Type here]`

## Other information:

`[Type here]`

2021-02-03 18:24 UTC, futurethang requested changes

2021-02-03 18:24 UTC, futurethang commented on Examples/Widgets/HospitalBedCapacity/src/components/HospitalWidget.ts
>                obj.types.forEach((t: any) => (seed[t] = obj.short_name)), seed
I'm confused about the `, seed` part at the end of this line . . . . seems like it is outside of the callback, but not a parameter of an outer function?

2021-02-03 18:24 UTC, futurethang commented on Examples/Widgets/HospitalBedCapacity/src/components/HospitalWidget.ts
>                obj.types.forEach((t: any) => (seed[t] = obj.short_name)), seed
I think we have an opportunity to improve the typing too, but that little bit was a wedge in my attempt

2021-02-05 18:47 UTC, futurethang commented on Examples/Widgets/HospitalBedCapacity/src/components/HospitalWidget.ts
> +    var ro = new ResizeObserver((entries: any) => {
Is there a funky-retro reason for using var with resizeObserver?

2021-02-10 03:10 UTC, yananym approved these changes

2021-02-10 03:10 UTC, merged